### ISSUE TITLE
Multi arch builds

### ISSUE THREAD

**Issue by williamdes** [legendu-net/docker-rustpython#10]
As discussed here: https://github.com/legendu-net/docker-rustpython/pull/9#issuecomment-1367722385

I use it on my image: https://github.com/sudo-bot/docker-phpldapadmin/blob/370c6f8b198f0e233e488c577d7d6a43bf24bd0e/docker/Dockerfile#L15

**Comment by dclong** [comment]
Thank you for the request! 

The pipeline for building this Docker image (and others) is at https://github.com/legendu-net/docker_image_builder/blob/dev/.github/workflows/build_images_regular.yml#L34. It leverages the Python library [dockeree](https://github.com/legendu-net/dockeree) to do the hard work. To support multi-arch, some refactoring work is required on [dockeree](https://github.com/legendu-net/dockeree). When [dockeree](https://github.com/legendu-net/dockeree) supports building multi-arch Docker images, we can then have add separate pipelines for different architectures. 

This is relatively lower priority on my TODO list. However, you are very welcome to submit a PR to [dockeree](https://github.com/legendu-net/dockeree) to make it support building multi-arch Docker images.

**Comment by williamdes** [comment]
Thank you, I will have a look
But we will need one pipeline that builds multiple architectures at once and writes the result into the registry. It can not be different pipelines.
Docker buildx does a very good job without changing much

**Comment by dclong** [comment]
One pipeline works as long as it doesn't take too much to run. I was thinking of separating different architectures into different pipelines because I have lots of Docker images to build and it already takes about 1.5-2 hours to run. Building all images for all architectures might take too long a time which exceeds the limit of GitHub Actions.

**Comment by williamdes** [comment]
You can extend the actions limits quite a lot, of even use self hosted runners
Why not having a separate build workflow on each repository?
Or at least on this repository for the alpine variant?

**Comment by dclong** [comment]
Self-hosted runners might make sense for companies or organizations but it doesn't make much sense to a single-personal developer. 

Building all Docker images together using one workflow has several advantages that I value (as explained in the PR https://github.com/legendu-net/docker-rustpython/pull/9). As a matter of fact, Docker images `dclong/*` was built separately before and then switched to this approach. I'm not convinced to switch back at this time. Given that said, it's OK to have a separate build workflow for the `alpine` branch of this repository only as the Docker image `dclong/rustpython:alpine` is an orphan among all Docker images `dclong/*`. There probably won't be many Docker images depend on it since RustPython is still very young.

**Comment by williamdes** [comment]
Okay, thank you for your kind feedback
I will build an image on my @sudo-bot organization for that. It will avoid you some complexity that is only due to my project requirements
